server:
  port: 8080
logging:
  file:
    path: ../../../logs

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/arknights
    username: root
    password: rootroot
    driver-class-name: com.mysql.cj.jdbc.Driver

springdoc:
  api-docs:
    enabled: true
  packages-to-scan:
    - xyz.keroro.chowder.dao.po
    - xyz.keroro.chowder.web.controller
    - xyz.keroro.chowder.domain.entity
#  mvc:
#    pathmatch:
#      matching-strategy: ANT_PATH_MATCHER