server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/arknights
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
#  mvc:
#    pathmatch:
#      matching-strategy: ANT_PATH_MATCHER