server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/chowder?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: rootroot
    driver-class-name: com.mysql.cj.jdbc.Driver