package rules
import com.keroro.chowder.domain.entity.vo.StudentVO
dialect  "java"

rule "lt60"
    when
        $stu: StudentVO((score < 60))
    then
        $stu.setScore(10F);
        update($stu)
        System.out.println("触发小于60的规则");
end

rule "ge60"
    when
        $stu: StudentVO(score >= 60 && score < 80)
    then
        $stu.setScore(90F);
        update($stu)
        System.out.println("触发60-80规则");
end

rule "ge80"
    when
        $stu: StudentVO(score >= 80)
    then
        System.out.println("触发大于等于80规则");
end

