server:
  port: 8100
logging:
  config: classpath:logback-spring-prod.xml
spring:
  application:
    name: Arknights
  datasource:
    url: jdbc:mysql://localhost:3307/arknights
    username: root
    password: XdhRFUtkhRN8a4A
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    inetutils:
#      不加这个默认会注册内网ip
      preferred-networks: 1.94.23
    nacos:
      discovery:
        server-addr: localhost:8473
        username: keroro
        password: keroro
        enabled: false
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
arknights:
  domain-as: https://as.hypergryph.com
  domain-ak: https://ak.hypergryph.com
  domain-web: https://web-api.hypergryph.com