server:
  port: 8100

arknights:
  domain-name: https://as.hypergryph.com

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/arknights
    username: root
    password: rootroot
    driver-class-name: com.mysql.cj.jdbc.Driver
