server:
  port: 8100
logging:
  config: classpath:logback-spring-dev.xml
spring:
  application:
    name: Arknights
  datasource:
    url: jdbc:mysql://localhost:3306/arknights
    username: root
    password: rootroot
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: keroro.xyz:8848
        username: keroro
        password: keroro
        failure-tolerance-enabled: true
#springdoc:
#  api-docs:
#    path: /api-docs
#  swagger-ui:
#    path: /swagger-ui.html
arknights:
  domain-as: https://as.hypergryph.com
  domain-ak: https://ak.hypergryph.com
  domain-web: https://web-api.hypergryph.com