server:
  port: 8100
logging:
  file:
    name: /root/logs/chowder/arknights/arknights.log
spring:
  application:
    name: Arknights
  datasource:
    url: jdbc:mysql://localhost:3307/arknights
    username: root
    password: XdhRFUtkhRN8a4A
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8473
        username: keroro
        password: keroro
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
arknights:
  domain-as: https://as.hypergryph.com
  domain-ak: https://ak.hypergryph.com
  domain-web: https://web-api.hypergryph.com