server:
  port: 8100
logging:
  file:
    name: /Users/wangpeng/MyCodeSpace/logs/arknights.log
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/arknights
    username: root
    password: rootroot
    driver-class-name: com.mysql.cj.jdbc.Driver
arknights:
  domain-as: https://as.hypergryph.com
  domain-ak: https://ak.hypergryph.com
  domain-web: https://web-api.hypergryph.com